# Generated by Django 2.2 on 2019-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yapilacaklarListesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', models.CharField(max_length=40)),
                ('tamamlama', models.BooleanField(default=False)),
            ],
        ),
    ]
